### ISSUE TITLE
Stack overflow or linker error when using bevy's `dynamic` feature

### ISSUE THREAD

**Issue by holly-hacker** [drakmaniso/bevy_pixel_camera#17]
When adding `bevy_pixel_camera` as a dependency and using bevy's `dynamic` feature, your project will either fail to build or crash on startup (presumably during dynamic linking).

This seems to be related to bevyengine/bevy#1110 but they seem to mention fairly specific setups, while the repro below crashes on stable rust with no custom configuration.

I understand this is likely not a bug in bevy_pixel_camera but rather in bevy_dylib, but I figured I'd open an issue to notify you of the problem. I won't mind if you choose to close this :)

## Minimal repro
Create a project with the files listed below, run using `cargo run --features bevy/dynamic` and observe a linker error mentioning "library limit of 65535 objects exceeded". Run using `cargo run` and everything works fine.

`Cargo.toml`
```toml
[package]
name = "bevy_pixel_camera_crash"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.8.1", default-features = false }
bevy_pixel_camera = "0.2.0"
```

`src/main.rs`
```rs
use bevy::prelude::*;

fn main() {
    App::new().add_system(|| println!("Hello world")).run();
}
```
